default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  port: 5432
  host: localhost
  username: postgres
  password: 12345678

development:
  <<: *default
  database: demo_page_development
